# Generated by Axiom CLI — do not delete.
# Ensures pytest can resolve "from nodes.<module> import <func>" imports
# whether tests are run from the package root or inside the Docker build.
import sys, os as _os
sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

import pytest


# ── Independent oracle ────────────────────────────────────────────────────────
# We build valid PDFs BY HAND here — writing the raw PDF object graph, content
# streams, and a correct xref table ourselves, with NO dependency on the library
# under test (pdfminer.six) or any other PDF library. Extraction that recovers
# the exact text and geometry we encoded is therefore checked against a
# ground truth that is independent of the implementation being tested.

def _pdf_obj(num: int, body: bytes) -> bytes:
    return f"{num} 0 obj\n".encode() + body + b"\nendobj\n"


def make_pdf(pages, x=72, y=700, font_size=24, width=612, height=792, info=None):
    """Return raw bytes of a valid multi-page PDF.

    `pages` is a list of one-line strings, one per page, each drawn with a Tj at
    (x, y) in PDF points on a width×height page. Object numbers are contiguous so
    a single-subsection xref covers them; byte offsets are computed exactly.
    `info`, if given, is a dict of info-dictionary entries (e.g. {"Title": ...})
    written as a PDF /Info object and referenced from the trailer.
    """
    n = len(pages)
    header = b"%PDF-1.4\n"
    objs, order = [], []

    objs.append(_pdf_obj(1, b"<< /Type /Catalog /Pages 2 0 R >>")); order.append(1)
    kids = " ".join(f"{4 + 2 * i} 0 R" for i in range(n))
    objs.append(_pdf_obj(2, f"<< /Type /Pages /Kids [{kids}] /Count {n} >>".encode()))
    order.append(2)
    objs.append(_pdf_obj(3, b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"))
    order.append(3)

    for i, text in enumerate(pages):
        pnum, cnum = 4 + 2 * i, 5 + 2 * i
        safe = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
        stream = f"BT /F1 {font_size} Tf {x} {y} Td ({safe}) Tj ET".encode()
        page = (f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {width} {height}] "
                f"/Contents {cnum} 0 R /Resources << /Font << /F1 3 0 R >> >> >>").encode()
        objs.append(_pdf_obj(pnum, page)); order.append(pnum)
        contents = (f"<< /Length {len(stream)} >>\nstream\n".encode()
                    + stream + b"\nendstream")
        objs.append(_pdf_obj(cnum, contents)); order.append(cnum)

    info_ref = ""
    if info:
        inum = max(order) + 1
        entries = "".join(
            "/{k} ({v})".format(
                k=k,
                v=str(v).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)"),
            )
            for k, v in info.items()
        )
        objs.append(_pdf_obj(inum, f"<< {entries} >>".encode())); order.append(inum)
        info_ref = f" /Info {inum} 0 R"

    out = bytearray(header)
    offsets = {}
    for num, ob in zip(order, objs):
        offsets[num] = len(out)
        out += ob

    xref_pos = len(out)
    size = max(order) + 1
    out += f"xref\n0 {size}\n".encode()
    out += b"0000000000 65535 f \n"
    for num in range(1, size):
        out += f"{offsets.get(num, 0):010d} 00000 n \n".encode()
    out += (f"trailer\n<< /Size {size} /Root 1 0 R{info_ref} >>\n"
            f"startxref\n{xref_pos}\n%%EOF").encode()
    return bytes(out)


class _Ctx:
    class _Logger:
        def debug(self, *a, **k): pass
        def info(self, *a, **k): pass
        def warn(self, *a, **k): pass
        def error(self, *a, **k): pass

    class _Secrets:
        def get(self, name): return ("", False)

    def __init__(self):
        self.log = self._Logger()
        self.secrets = self._Secrets()
        self.execution_id = "test-execution-id"
        self.flow_id = "test-flow-id"
        self.tenant_id = "test-tenant-id"


@pytest.fixture
def ax():
    return _Ctx()


@pytest.fixture
def pdf_bytes():
    """Function that builds a hand-authored PDF (the oracle)."""
    return make_pdf


@pytest.fixture
def simple_pdf():
    """One page containing the exact string 'Hello Axiom' at (72, 700)."""
    return make_pdf(["Hello Axiom"])


@pytest.fixture
def three_page_pdf():
    """Three pages with distinct known text at known positions."""
    return make_pdf(["Page one alpha", "Page two beta", "Page three gamma"])


@pytest.fixture
def pdf_with_metadata():
    """Two-page PDF with a known /Info dictionary (the metadata oracle)."""
    return make_pdf(
        ["Report body", "Appendix"],
        info={
            "Title": "Quarterly Report",
            "Author": "Ada Lovelace",
            "Subject": "Finance",
            "Creator": "AxiomTest",
            "Producer": "pdf-tools-test",
            "Keywords": "q1 finance report",
        },
    )
